<<<<<<< HEAD
# Generated by Django 2.2.17 on 2021-01-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210108_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='role'),
        ),
    ]
=======
# Generated by Django 2.2.17 on 2021-01-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210108_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='role'),
        ),
    ]
>>>>>>> deployment-backup
