# Generated by Django 2.2.17 on 2021-01-08 12:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210108_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repositorysearch',
            name='repository',
        ),
        migrations.AddField(
            model_name='repositorysearch',
            name='key',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='tag'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kotdarepositoryresource',
            name='type',
            field=models.CharField(choices=[('Investor journey', 'Investor journey'), ('Key events', 'Key events'), ('Project milestones', 'Project milestones'), ('Innovation ecosystem', 'Innovation ecosystem'), ('Miscellaneous', 'Miscellaneous')], default='unspecified', max_length=50),
        ),
    ]
