# Generated by Django 2.2.17 on 2021-01-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210108_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kotdarepositoryresource',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='kotdarepositoryresource',
            name='featured_image',
        ),
        migrations.AlterField(
            model_name='kotdarepositoryresource',
            name='type',
            field=models.CharField(blank=True, choices=[('Investor journey', 'Investor journey'), ('Key events', 'Key events'), ('Project milestones', 'Project milestones'), ('Innovation ecosystem', 'Innovation ecosystem'), ('Miscellaneous', 'Miscellaneous')], max_length=50, null=True),
        ),
    ]
