# Generated by Django 2.2.17 on 2021-01-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210108_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='kotdarepositoryresource',
            name='upload_type',
            field=models.CharField(choices=[('document', 'document'), ('video', 'video'), ('image', 'image'), ('url', 'url')], default='document', max_length=50),
        ),
    ]
