# Generated by Django 2.2.17 on 2021-01-12 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_kotdarepositoryresource_upload_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kotdarepositoryresource',
            name='doc_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.RepositoryDocumentType', verbose_name='doc type'),
        ),
    ]
