# Generated by Django 2.2.17 on 2021-01-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210112_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kotdarepositoryresource',
            name='upload_type',
            field=models.CharField(blank=True, choices=[('document', 'document'), ('video', 'video'), ('image', 'image'), ('url', 'url')], default='document', max_length=50),
        ),
    ]
