# Generated by Django 2.2.17 on 2021-01-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_repositorydocumentdownloadstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio_ispublic',
            field=models.BooleanField(default=False),
        ),
    ]
