<<<<<<< HEAD
# Generated by Django 2.2.17 on 2021-01-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_profile_bio_ispublic'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositoryresourcevideourl',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='repoImages/'),
        ),
    ]
=======
# Generated by Django 2.2.17 on 2021-01-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_profile_bio_ispublic'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositoryresourcevideourl',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='repoImages/'),
        ),
    ]
>>>>>>> deployment-backup
