# Generated by Django 2.2.17 on 2021-01-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_repositorydocumenttype_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositorydocumenttype',
            name='access_level',
            field=models.CharField(choices=[('Public', 'Public'), ('Protected', 'Protected'), ('Private', 'Private')], default='Public', max_length=50),
        ),
    ]
