# Generated by Django 2.2.17 on 2021-01-22 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_repositorydocumenttype_is_static'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kotdarepositoryresource',
            name='type',
        ),
    ]
