<<<<<<< HEAD
# Generated by Django 2.2.17 on 2021-01-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_kotdarepositoryresource_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kotdarepositoryresource',
            name='access_level',
            field=models.CharField(blank=True, choices=[('Public', 'Public'), ('Protected', 'Protected'), ('Private', 'Private')], default='Private', max_length=50, null=True),
        ),
    ]
=======
# Generated by Django 2.2.17 on 2021-01-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_kotdarepositoryresource_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kotdarepositoryresource',
            name='access_level',
            field=models.CharField(blank=True, choices=[('Public', 'Public'), ('Protected', 'Protected'), ('Private', 'Private')], default='Private', max_length=50, null=True),
        ),
    ]
>>>>>>> deployment-backup
