<<<<<<< HEAD
# Generated by Django 2.2.17 on 2021-01-22 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20210122_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryDocumentFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=50, verbose_name='folder name')),
                ('description', models.TextField(blank=True, max_length=50000, null=True, verbose_name='description')),
                ('access_level', models.CharField(choices=[('Public', 'Public'), ('Protected', 'Protected'), ('Private', 'Private')], default='Protected', max_length=50)),
                ('is_static', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
        ),
        migrations.AlterField(
            model_name='documentfolderrelationship',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='app.RepositoryDocumentFolder', verbose_name='parent'),
        ),
        migrations.AlterField(
            model_name='documentfolderrelationship',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='app.RepositoryDocumentFolder', verbose_name='parent'),
        ),
        migrations.AlterField(
            model_name='kotdarepositoryresource',
            name='doc_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.RepositoryDocumentFolder', verbose_name='doc type'),
        ),
        migrations.DeleteModel(
            name='RepositoryDocumentType',
        ),
    ]
=======
# Generated by Django 2.2.17 on 2021-01-22 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20210122_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryDocumentFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=50, verbose_name='folder name')),
                ('description', models.TextField(blank=True, max_length=50000, null=True, verbose_name='description')),
                ('access_level', models.CharField(choices=[('Public', 'Public'), ('Protected', 'Protected'), ('Private', 'Private')], default='Protected', max_length=50)),
                ('is_static', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
        ),
        migrations.AlterField(
            model_name='documentfolderrelationship',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='app.RepositoryDocumentFolder', verbose_name='parent'),
        ),
        migrations.AlterField(
            model_name='documentfolderrelationship',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='app.RepositoryDocumentFolder', verbose_name='parent'),
        ),
        migrations.AlterField(
            model_name='kotdarepositoryresource',
            name='doc_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.RepositoryDocumentFolder', verbose_name='doc type'),
        ),
        migrations.DeleteModel(
            name='RepositoryDocumentType',
        ),
    ]
>>>>>>> deployment-backup
