# Generated by Django 2.2.17 on 2021-01-24 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20210122_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentFolderRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Department')),
            ],
        ),
        migrations.RenameField(
            model_name='kotdarepositoryresource',
            old_name='doc_type',
            new_name='department_folder',
        ),
        migrations.AlterField(
            model_name='repositorydocumentfolder',
            name='folder_name',
            field=models.CharField(default='New Folder', max_length=50, verbose_name='folder name'),
        ),
        migrations.DeleteModel(
            name='DocumentFolderRelationship',
        ),
        migrations.AddField(
            model_name='departmentfolderrelationship',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder', to='app.RepositoryDocumentFolder', verbose_name='folder'),
        ),
        migrations.AlterUniqueTogether(
            name='departmentfolderrelationship',
            unique_together={('folder', 'department')},
        ),
    ]
