# Generated by Django 2.2.17 on 2021-02-03 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20210124_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentfolderrelationship',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='app.RepositoryDocumentFolder'),
        ),
        migrations.AlterUniqueTogether(
            name='departmentfolderrelationship',
            unique_together={('folder', 'department', 'parent')},
        ),
    ]
