# Generated by Django 2.2.17 on 2021-02-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20210203_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kotdarepositoryresource',
            name='upload_type',
            field=models.CharField(blank=True, choices=[('document', 'document'), ('video', 'video'), ('image', 'image')], default='document', max_length=50),
        ),
        migrations.AlterField(
            model_name='repositoryresourcevideourl',
            name='name_of_video',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='title of video'),
        ),
    ]
