# Generated by Django 2.2.17 on 2021-03-08 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20210226_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='kotdarepositoryresource',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_deleted_by', to=settings.AUTH_USER_MODEL, verbose_name='deleted by'),
        ),
        migrations.AddField(
            model_name='repositorydocumentfolder',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder_deleted_by', to=settings.AUTH_USER_MODEL, verbose_name='deleted by'),
        ),
        migrations.AddField(
            model_name='repositoryresourcedownload',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_deleted_by', to=settings.AUTH_USER_MODEL, verbose_name='deleted by'),
        ),
        migrations.AddField(
            model_name='repositoryresourceimage',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_deleted_by', to=settings.AUTH_USER_MODEL, verbose_name='deleted by'),
        ),
        migrations.AddField(
            model_name='repositoryresourcevideourl',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_deleted_by', to=settings.AUTH_USER_MODEL, verbose_name='deleted by'),
        ),
        migrations.AlterField(
            model_name='departmentfolderrelationship',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relationship_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kotdarepositoryresource',
            name='access_level',
            field=models.CharField(blank=True, choices=[('Public', 'Public'), ('Internal ', 'Internal'), ('Restricted', 'Restricted'), ('Confidential', 'Confidential')], default='Internal', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kotdarepositoryresource',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='access_level',
            field=models.CharField(choices=[('Public', 'Public'), ('Internal ', 'Internal'), ('Restricted', 'Restricted'), ('Confidential', 'Confidential')], default='Internal', max_length=50),
        ),
        migrations.AlterField(
            model_name='repositorydocumentfolder',
            name='access_level',
            field=models.CharField(choices=[('Public', 'Public'), ('Internal ', 'Internal'), ('Restricted', 'Restricted'), ('Confidential', 'Confidential')], default='Internal', max_length=50),
        ),
        migrations.AlterField(
            model_name='repositorydocumentfolder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='repositoryresourcedownload',
            name='access_level',
            field=models.CharField(choices=[('Public', 'Public'), ('Internal ', 'Internal'), ('Restricted', 'Restricted'), ('Confidential', 'Confidential')], default='Public', max_length=50),
        ),
        migrations.AlterField(
            model_name='repositoryresourceimage',
            name='access_level',
            field=models.CharField(choices=[('Public', 'Public'), ('Internal ', 'Internal'), ('Restricted', 'Restricted'), ('Confidential', 'Confidential')], default='Public', max_length=50),
        ),
        migrations.AlterField(
            model_name='repositoryresourcereferenceurl',
            name='access_level',
            field=models.CharField(choices=[('Public', 'Public'), ('Internal ', 'Internal'), ('Restricted', 'Restricted'), ('Confidential', 'Confidential')], default='Public', max_length=50),
        ),
        migrations.AlterField(
            model_name='repositoryresourcevideourl',
            name='access_level',
            field=models.CharField(choices=[('Public', 'Public'), ('Internal ', 'Internal'), ('Restricted', 'Restricted'), ('Confidential', 'Confidential')], default='Public', max_length=50),
        ),
        migrations.AlterField(
            model_name='repositoryresourcevideourl',
            name='name_of_video',
            field=models.CharField(blank=True, default='UNTITLED', max_length=50, null=True, verbose_name='title of video'),
        ),
    ]
