# Generated by Django 2.2.17 on 2021-03-31 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20210308_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositoryresourcedownload',
            name='name_of_document',
            field=models.CharField(max_length=5000, verbose_name='name of document'),
        ),
    ]
