# Generated by Django 2.2.17 on 2021-04-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20210331_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kotdarepositoryresource',
            name='access_level',
            field=models.CharField(blank=True, choices=[('Public', 'Public'), ('Internal ', 'Internal'), ('Restricted', 'Restricted')], default='Internal', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kotdarepositoryresource',
            name='title',
            field=models.CharField(max_length=500, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='access_level',
            field=models.CharField(choices=[('Public', 'Public'), ('Internal ', 'Internal'), ('Restricted', 'Restricted')], default='Internal', max_length=50),
        ),
        migrations.AlterField(
            model_name='repositorydocumentfolder',
            name='access_level',
            field=models.CharField(choices=[('Public', 'Public'), ('Internal ', 'Internal'), ('Restricted', 'Restricted')], default='Internal', max_length=500),
        ),
        migrations.AlterField(
            model_name='repositorydocumentfolder',
            name='folder_name',
            field=models.CharField(default='New Folder', max_length=5000, verbose_name='folder name'),
        ),
        migrations.AlterField(
            model_name='repositoryresourcedownload',
            name='access_level',
            field=models.CharField(choices=[('Public', 'Public'), ('Internal ', 'Internal'), ('Restricted', 'Restricted')], default='Public', max_length=50),
        ),
        migrations.AlterField(
            model_name='repositoryresourceimage',
            name='access_level',
            field=models.CharField(choices=[('Public', 'Public'), ('Internal ', 'Internal'), ('Restricted', 'Restricted')], default='Public', max_length=50),
        ),
        migrations.AlterField(
            model_name='repositoryresourceimage',
            name='name_of_image',
            field=models.CharField(blank=True, default='UNTITLED', max_length=50000, null=True, verbose_name='name of document'),
        ),
        migrations.AlterField(
            model_name='repositoryresourcereferenceurl',
            name='access_level',
            field=models.CharField(choices=[('Public', 'Public'), ('Internal ', 'Internal'), ('Restricted', 'Restricted')], default='Public', max_length=50),
        ),
        migrations.AlterField(
            model_name='repositoryresourcevideourl',
            name='access_level',
            field=models.CharField(choices=[('Public', 'Public'), ('Internal ', 'Internal'), ('Restricted', 'Restricted')], default='Public', max_length=50),
        ),
        migrations.AlterField(
            model_name='repositoryresourcevideourl',
            name='name_of_video',
            field=models.CharField(blank=True, default='UNTITLED', max_length=50000, null=True, verbose_name='title of video'),
        ),
        migrations.AlterField(
            model_name='repositorysearch',
            name='key',
            field=models.CharField(max_length=10000, verbose_name='tag'),
        ),
    ]
